# Generated by Django 3.2.9 on 2021-11-26 13:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage('/media/tb'), upload_to='')),
            ],
        ),
    ]
