# Generated by Django 3.2.9 on 2022-01-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbot', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя пользователя'),
        ),
    ]
